Add debian packaging
reddit/fluent-plugin-logdna pull request #1
Opened 2018-05-08 23:37 UTC by rram

I'm not terribly pleased with the rake/makefile mess and am happy to hear ideas for improvement/cleanliness.

👓 @ckwang8128 @qbrian @spladug

2018-05-09 18:02 UTC, spladug approved these changes
with one nit. seems pretty reasonable to me!

2018-05-09 18:02 UTC, spladug commented on fluent-plugin-logdna.gemspec
> +  s.version     = '0.1.8'
i think we want to do 0.1.7.1? i'm worried that this packaging will conflict with whenever upstream releases 0.1.8

2018-05-09 23:34 UTC, ckwang8128 commented on Makefile
> +	  pkg/*.gem $(GEMFILE)
Are there any non-standard flags here for FPM-ing Ruby stuff? If so, could you add a comment about why the flags are needed?

2018-05-09 23:39 UTC, ckwang8128 requested changes
I know we went over most of this in person, but it'd be great if you could add a README or something additional in the Make/Rakefile comments about the hoops that you had to jump through to generate this. 

Just this and my other comment about adding some docs. The structure itself looks okay to me!

2018-05-14 20:26 UTC, ckwang8128 approved these changes

2018-05-14 22:08 UTC, merged